### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by merlinuwe** [guopenghui/obsidian-quiet-outline#154]
Thanks for your great plugin.

Today, I got this error message:

![image](https://github.com/guopenghui/obsidian-quiet-outline/assets/4138869/e5ffe614-fff4-456e-a261-9e52130116ba)

Do you have an idea where it comes from?

**Comment by guopenghui** [comment]
Fixed.

When obsidian is initializing, it runs initializing code of plugins. But during this time, some of obsidian's components is not ready to use, in this case, like `workspace.RightSplit` is null so reading `children` from it will throw an error.

**Comment by drflo3** [comment]
Hello, 
The fix for this ticket introduced a new bug : 
Every time I open Obsidian I have a new QuietOutline side window opened on the right panel.
So it opens my side panel whereas I closed Obsidian with the side panel closed.
And it mess it up with multiple QuietOuline instances.

Thanks for the help

**Comment by guopenghui** [comment]
@drflo3 I made a fix in 0.3.22, could you test for it so make sure there are no more bugs? 😵

**Comment by drflo3** [comment]
Hi, 
I don't notice anymore any problem.
Thanks for the great work.

**Comment by merlinuwe** [comment]
Me too. No messages in the console anymore. Thank you very much for solving! ;-)
