### ISSUE TITLE
Updating plugin moves it in the sidebars

### ISSUE THREAD

**Issue by Smitty010** [guopenghui/obsidian-quiet-outline#179]
I like "quiet outline" to be in be in bottom of my left sidebar.  Every time I update it to a new version, it gets moved to the top of the right sidebar.  Not a show stopper, but annoying.

**Comment by guopenghui** [comment]
Previously, many people wanted the outline panel to open immediately when launching the plugin (see the issues about "why I don't have an outline panel here"), so this was set in later implementations.
This conflicts with your needs, because if the panel opens immediately when you start the plugin, you need to set a default position, which is the right sidebar. When you update the plugin, it is equivalent to closing and opening the plugin, so the outline panel will return to its "default position".

Both needs are valid, but it's not possible to fulfill both at the moment. I'll keep an eye on this until it has a good solution

**Comment by guopenghui** [comment]
see release message in `0.3.35`

**Comment by Smitty010** [comment]
Thanks
