### ISSUE TITLE
[FR] Option to focus Auto Expand and Heading Highlighting at Cursor position instead of scroll position

### ISSUE THREAD

**Issue by Glint-Eye** [guopenghui/obsidian-quiet-outline#84]
Like the title says, it would be great if there was an option to focus the auto expanding around the cursor position. Usually I am more interested in the position of my cursor and the "scroll off point" to indicate a heading change rarely points to the correct heading i am currently working on.

Another interesting option would be mix of both. Focus on cursor after any kind of cursor position change or input and focus on scroll position after scrolling input.

Thanks for the great plugin though :)

**Comment by guopenghui** [comment]
> all IDE software highlight outline by cursor position

Show some example please. As what I know, typora uses scroll position instead of cursor position.

**Comment by hihihlo** [comment]
below are some example :
- SlickEdit : tested for .cpp
- Source Insight : tested for .cpp
- EmEditor : I use it every day (although it is just a text editor)
- Vim (TagList) :  https://www.eclipse.org/forums/index.php/t/886403/
- Eclipse  outline view :  https://www.eclipse.org/forums/index.php/t/886403/
  (with check on "Link with editor") 
- vscode buildin outline :
  I tested for .md & .py & .cpp  (with check on "follow cursor")

Those software highlight current scope in outline when cursor move between text area,
they are very exact.
I don't know why typora uses scroll position instead of cursor position,
maybe that is his implements limit ?

**Comment by guopenghui** [comment]
Latest version should fix this issue, so close it.
