### ISSUE TITLE
Heading levels reset on launch

### ISSUE THREAD

**Issue by NomarCub** [guopenghui/obsidian-quiet-outline#9]
I'd like to use the outline as fully expanded on all levels by default. Without the Level Switch Bar, when I reload the app only the topmost headings show. With it, the slider resets to h1 on every reload too.

**Comment by guopenghui** [comment]
I'll consider it. Maybe add a setting to customizing.

By the way, I wonder what's your favorate part of this plugin or why you enjoy using it. The first reason I created it is to make outline not always expand on all levels, because most of my notes have so many headings, searching in a long outline list is painful.

Thanks for your suggestion.

**Comment by NomarCub** [comment]
My favourite part is the markdown rendering. I also like the collapsing, but I'd never collapse to h1, which is the default, because I only have titles at that level. (Most of my notes don't even have any h1, but the ones that do are important and I use them often.) Not resetting on launch, or having a setting for a default level would be ideal for my use case.

**Comment by guopenghui** [comment]
Fixed in `v0.2.1`
