### ISSUE TITLE
Clicking a section always selects the section *above* that section

### ISSUE THREAD

**Issue by ajh3** [guopenghui/obsidian-quiet-outline#99]
See video:

https://user-images.githubusercontent.com/40405382/220735727-510d113d-4b49-411b-b38f-f4d79941d83b.mp4

SYSTEM INFO:
	Obsidian version: v1.1.15
	Installer version: v1.1.15
	Operating system: Windows 10 Pro 10.0.19045
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: off
	Legacy editor: off
	Base theme: light
	Community theme: AnuPpuccin v1.3.1
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 7
	Plugins enabled: 5
		1: Settings Search v1.3.6
		2: Quiet Outline v0.3.15
		3: Influx v2.1.2
		4: Style Settings v1.0.3
		5: Kanban v1.5.2

**Comment by bonfiresh** [comment]
on mobile device，the same issue

**Comment by guopenghui** [comment]
I think it's because this plugin can't find the precise *current location*. It use the 8th line in view as the divider. When you click "AM questions"，this heading appear on the middle of view, but it's under the 8th line so "SA terminology" is treated as the *current location*.

Obsidian API doesn't offer an API to get lines count in view, so 8th-line is a rough workaround.

**Comment by ajh3** [comment]
Possibly related? https://forum.obsidian.md/t/toc-navigation-when-selecting-a-header-the-header-above-gets-highlighted/13662

**Comment by thejamesm** [comment]
I'm guessing Obsidian is hard-coded to scroll the heading to the centre of the pane. Personally I think it would be better to place it nearer the top (similar to the 8th line measure), since readers are far more likely to be interested in what's below the heading they clicked on than what's above. If it _is_ possible to override the default scroll-to behaviour, I would suggest doing so to match the heading highlighting.

**Comment by guopenghui** [comment]
Latest version should fix this issue, so close it.
